### ISSUE TITLE
config dir is ignored

### ISSUE THREAD

**Issue by muzzol** [blroot/adtool#1]
I've tried several options with **--sysconfdir** and **--prefix** and adtool always look at two fixed locations:

```
~/.adtool.cfg
/usr/local/etc/adtool.cfg
```

I've rechecked with **strace**.

this makes impossible for a single user to use 2 different settings even with 2 compilations.

maybe cfg file could be an additional parameter

**Comment by blroot** [comment]
Im sorry, i am not the original author of this project, and is not under my maintenance, feel free to fork this repository if you want to make contributions.
