### ISSUE TITLE
Create a domain local distribution group

### ISSUE THREAD

**Issue by magostinelli** [blroot/adtool#2]
Hello,
Inside active directory the are different type of grou, i need to cerate a domain local distribution group.

I tryed to modify your code, but a obtain a segmentation fault.

My modification was:
src/lib/active_directory.c
...
int ad_group_create(char *group_name, char *dn) {
       LDAPMod *attrs[5];
        LDAPMod attr1, attr2, attr3, attr4, attr5;

....
        sAMAccountType_values[0]="536870912";
        sAMAccountType_values[1]=NULL;
        attr4.mod_op = LDAP_MOD_ADD;
        attr4.mod_type = "sAMAccountType";
        attr4.mod_values = sAMAccountType_values;

        attrs[0]=&attr1;
        groupType_values[0]="2147483644";
        groupType_values[1]=NULL;
        attr5.mod_op = LDAP_MOD_ADD;
        attr5.mod_type = "groupType";
        attr5.mod_values = groupType_values;

        attrs[0]=&attr1;
        attrs[1]=&attr2;
        attrs[2]=&attr3;
        attrs[3]=&attr4;
        attrs[4]=&attr5;
        attrs[5]=NULL;
....

I obtain:
error: Error in ldap_add: Server is unwilling to perform

I can read this two links:
https://docs.microsoft.com/en-us/windows/win32/adschema/a-grouptype
https://ldapwiki.com/wiki/GroupType

I think the best option is to add an optional parameter (groupType) to:
groupcreate        <group name> <container>        create a new group

I don't know if groupType or also sAMAccountType is needed.

Regards.

**Comment by blroot** [comment]
Im sorry, i am not the original author of this project, and is not under my maintenance, feel free to fork this repository if you want to make contributions.
